### ISSUE TITLE
Add all-in-one Nextcloud support to Online Accounts

### ISSUE THREAD

**Issue by dnisbetjones** [elementary/switchboard-plug-onlineaccounts#178] opened 2021-05-29 18:13 UTC
## Proposal

I think it would be great to include an all-in-one Nextcloud account connection in Online Accounts, ala. GNOME. I saw the inclusion of CalDAV coming to eOS 6 Beta 2 but beyond pulling the calendars and tasks out it would be great to automatically pull contacts, files and things like notes to integrate with all of the awesome Curated Apps in elementary.

**Comment by danrabbit** [comment] 2021-06-01 22:24
Closing as a duplicate of #16

**Closed by danrabbit** 2021-06-01 22:24 UTC
