### ISSUE TITLE
Last.fm scrobbling broken

### ISSUE THREAD

**Issue by aadilayub** [elementary/switchboard-plug-onlineaccounts#93] opened 2019-04-18 19:34 UTC
Not sure if this is related to https://github.com/elementary/switchboard-plug-onlineaccounts/issues/92

The toggle for turning on Last.fm scrobbling keeps turning off. Here is what it looks when I try to turn it on:

![image](https://user-images.githubusercontent.com/31581044/56386391-123b9d00-623b-11e9-8833-1817e1ead061.png)

Here is what it looks like after I close and open the system settings app and navigate to online accounts:

![image](https://user-images.githubusercontent.com/31581044/56386470-4747ef80-623b-11e9-9618-2e6782ee90b5.png)

To confirm, I double-checked my last.fm account and none of the tracks I listen to on Music are showing up in my listening history. I'm able to reproduce this behavior 90% of the time. The other times, the toggle stays on in system settings but the tracks still don't get scrobbled.

**Comment by aadilayub** [comment] 2019-05-06 14:46
![Screenshot from 2019-05-06 19-45-23](https://user-images.githubusercontent.com/31581044/57233174-8fd31b80-7037-11e9-887e-bdc5ff42e6ea.png)

Update: Now the switchboard shows the integration as active in system settings, but none of the tracks get scrobbled to Last.fm

**Comment by yahoo1999** [comment] 2019-12-09 10:01
I'm having same problem. Scrobbling settings reset every time I close Switchboard. gdb doesn't show any errors. 
OS: elementary OS 5.1 Hera
Switchboard v2.3.7

**Comment by ghabit** [comment] 2019-12-28 10:11
1. It is impossible to remove last.fm account, after restarting switchboard it appearing again.
2. It is impossible to switch on scrobbling option, it does not working, and after restarting switchboard this option appears as switched off.
Don't know if it helps, output of console-starting command and trying to remove last.fm accounts:
```
:~$ G_MESSABES_DEBUG=all io.elementary.switchboard
** (io.elementary.switchboard:11256): WARNING **: 13:00:39.004: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:39.004: ACListBox.vala:54: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): WARNING **: 13:00:42.689: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '3'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:42.689: ACListBox.vala:54: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '3'
** (io.elementary.switchboard:11256): WARNING **: 13:00:44.425: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:44.425: ACListBox.vala:54: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): WARNING **: 13:00:45.813: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:45.813: ACListBox.vala:54: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): WARNING **: 13:00:47.258: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '3'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:47.258: AccountsManager.vala:78: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '3'
** (io.elementary.switchboard:11256): WARNING **: 13:00:47.262: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:47.262: ACListBox.vala:54: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): WARNING **: 13:00:49.079: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:49.079: ACListBox.vala:54: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): WARNING **: 13:00:53.412: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
** (io.elementary.switchboard:11256): CRITICAL **: 13:00:53.412: AccountsManager.vala:78: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityNotFound: identity not found with id '7'
(io.elementary.switchboard:11256): Gtk-WARNING **: 13:00:53.412: Child name 'main' not found in GtkStack
```
is there some workaround to get last.fm scrobbling working with noise\music? Thank you.

**Comment by danrabbit** [comment] 2021-05-24 19:18
Thanks for your report! We're doing a from-scratch rewrite of Online Accounts and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Online Accounts

**Closed by danrabbit** 2021-05-24 19:18 UTC
