### ISSUE TITLE
Broken icon

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/switchboard-plug-onlineaccounts#143] opened 2021-01-26 07:20 UTC
## What Happened

Email has broken icon due to elementary/icons#995. The provider uses `internet-mail` for certain providers, causing icon breakage.
![Screenshot from 2021-01-26 15-11-25](https://user-images.githubusercontent.com/31680656/105812251-c6f61700-5fe8-11eb-8d8b-fb708ef8a075.png)

## Expected Behavior

There should be an icon.

## Proposal

This was previously the Mail app icon itself, but I don't think this should be the case since you'd want to discern the actual app from a provider. Maybe fallback to `emblem-mail`?
![Screenshot from 2021-01-26 15 17 42](https://user-images.githubusercontent.com/31680656/105812733-aa0e1380-5fe9-11eb-8da5-e3f7c5ed5534.png)

Or elementary/icons#995 could be reverted, or just symlinked back to `io.elementary.mail`.

## Steps to Reproduce

1. Open Online Accounts Switchboard plug.
2. Add account

## Logs
```
** (io.elementary.switchboard:29689): DEBUG: 15:10:43.112: ProviderRow.vala:42: Provider Email icon name: internet-mail
** (io.elementary.switchboard:29689): DEBUG: 15:10:43.113: ProviderRow.vala:42: Provider Fastmail icon name: online-account-fastmail
** (io.elementary.switchboard:29689): DEBUG: 15:10:43.113: ProviderRow.vala:42: Provider Microsoft icon name: online-account-microsoft
** (io.elementary.switchboard:29689): DEBUG: 15:10:43.113: ProviderRow.vala:42: Provider Last.fm icon name: online-account-lastfm
** (io.elementary.switchboard:29689): DEBUG: 15:10:43.113: ProviderRow.vala:42: Provider Facebook icon name: online-account-facebook
** (io.elementary.switchboard:29689): DEBUG: 15:10:43.113: ProviderRow.vala:42: Provider Google icon name: online-account-google
```

## Platform Information
eOS6 daily

**Comment by pongloongyeat** [comment] 2021-01-26 07:39
Here as well

https://github.com/elementary/switchboard-plug-onlineaccounts/blob/0910037ee187c5dc5c766e72dea5004708e606ff/src/Views/AccountView.vala#L45

**Comment by danrabbit** [comment] 2021-05-24 19:18
Thanks for your report! We're doing a from-scratch rewrite of Online Accounts and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Online Accounts

**Closed by danrabbit** 2021-05-24 19:18 UTC
