### ISSUE TITLE
Online Accounts

### ISSUE THREAD

**Issue by ActionableEd** [elementary/switchboard-plug-onlineaccounts#135] opened 2020-05-04 19:49 UTC
I currently have to active email accounts setup in Mail.  I was using a fastmail account but deleted it.  Now I cannot remove the fastmail account from online accounts and my second email address does not show up.

When I try to remove the fastmail account I get the acknowledgement but the next time I open the page it reappears..   Do I have a file locked somewhere?
![reappear](https://user-images.githubusercontent.com/64807210/81007197-ceeca600-8e1e-11ea-993b-1b1d5fc8d862.jpeg)

**Comment by yerbestpal** [comment] 2020-06-27 23:48
Sounds like a Duplicate of #137

**Comment by danrabbit** [comment] 2021-05-25 23:46
Thanks for your report! We're doing a from-scratch rewrite of Online Accounts and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Online Accounts

**Closed by danrabbit** 2021-05-25 23:46 UTC
