### ISSUE TITLE
Unable to remove the only online account I have

### ISSUE THREAD

**Issue by persello** [elementary/switchboard-plug-onlineaccounts#137] opened 2020-05-24 15:12 UTC
Even logging out and back in or rebooting the device does not solve the issue.
I attach a short recording of what happens (don't worry about the address, it's the one I use on GitHub).

![Screen record from 2020-05-24 17 01 58](https://user-images.githubusercontent.com/45900950/82757562-830b9c00-9de1-11ea-91e9-2fb02a7db1f2.gif)

**Comment by yerbestpal** [comment] 2020-06-27 23:47
I am not actually able to remove **any** accounts.

**Comment by lowski** [comment] 2020-12-22 16:36
@persello @yerbestpal I had the [very similar issue](https://www.reddit.com/r/elementaryos/comments/khyahm/unable_to_remove_online_account/) and was able to fix it by removing following directories:

- `~/.config/autostart/pantheon-mail-autostart.desktop`
- `~/.config/libaccounts-glib`

I'm not fully sure what else is stored in `~/.config/libaccounts-glib` so I recommend to backup it first.

**Comment by riker09** [comment] 2021-04-13 12:01
I have had a look inside the SQlite database in `~/.config/libaccounts-glib/accounts.db` (the only file inside that folder, if you don't count the zero-sized journal file). It holds the account I created, but only the name. no configuration, no password, nothing. I was looking for a way to change the port I had entered when initially creating the account. But there is no way to do this via the GUI (or at least none that I could find) and the database is empty as well?

**Comment by selwynorren** [comment] 2021-05-06 23:29
I have the same issue, I have only loaded one IMAP account, but not able to delete it at all

**Comment by danrabbit** [comment] 2021-05-24 19:17
Thanks for your report! We're doing a from-scratch rewrite of Online Accounts and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Online Accounts

**Closed by danrabbit** 2021-05-24 19:17 UTC
