### ISSUE TITLE
I created an IMAP account and now cand add or delete any account.

### ISSUE THREAD

**Issue by efdiloreto** [elementary/switchboard-plug-onlineaccounts#131] opened 2020-04-10 13:20 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I added an IMAP account and now I can't delete or add any online account.

### Expected behavior
Delete the existing account and be able to add others like Last.fm.

### Screenshots or screen recordings
![Screenshot de 2020-04-10 10-14-41](https://user-images.githubusercontent.com/23631382/78993467-1fb8f980-7b14-11ea-93a2-f8964689943e.png)

## Platform Information
 - OS: [elementary OS]
 - OS Version [Hera 5.1.3]

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danrabbit** [comment] 2021-05-24 19:56
Thanks for your report! We're doing a from-scratch rewrite of Online Accounts and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Online Accounts.

**Closed by danrabbit** 2021-05-24 19:56 UTC
