### ISSUE TITLE
Online account not linked to anything

### ISSUE THREAD

**Issue by omeomi** [elementary/switchboard-plug-onlineaccounts#145] opened 2021-02-26 11:31 UTC
## What Happened

After adding my Fastmail account (either using an app password or the main password) the account is shown in the list of Online Accounts but is not linked to Mail (or anything else for that matter). The same occurs when I add an IMAP account. As a result, when I open Mail it keeps asking to connect an Online Account instead of showing the email for the already added account(s).

**Online Account screen after adding my account:**
![onlineaccounts](https://user-images.githubusercontent.com/3791259/109294794-92fb5500-7825-11eb-9460-f4367e2e3b27.png)

## Expected Behavior

The added account get linked to the Mail application and my email shows up in Mail.

## Steps to Reproduce

1. Click on '+ Add account' button in the Online Accounts screen
2. Choose either Fastmail or Email (same result either way)
3. Enter information

### Logs

These are the logs that occur when adding the account (I removed the SSO identity IDs, not sure if that is sentitive information or not):
```
** (io.elementary.switchboard:8237): WARNING **: 11:19:52.073: PasswordDialog.vala:307: RequestId

** (io.elementary.switchboard:8237): WARNING **: 11:19:52.073: PasswordDialog.vala:307: ForgotPasswordUrl

** (io.elementary.switchboard:8237): WARNING **: 11:19:52.073: PasswordDialog.vala:307: SignUpURL

** (io.elementary.switchboard:8237): WARNING **: 11:19:52.073: PasswordDialog.vala:307: QueryPassword

** (io.elementary.switchboard:8237): WARNING **: 11:19:52.073: PasswordDialog.vala:307: DisplayName

** (io.elementary.switchboard:8237): WARNING **: 11:19:52.073: PasswordDialog.vala:307: QueryUserName
** (io.elementary.switchboard:8237): DEBUG: 11:19:57.691: ../libsignon-glib/signon-identity.c:317: identity_remote_object_destroyed_cb 317
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.137: ../libsignon-glib/signon-identity.c:697: 
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.170: ../libsignon-glib/signon-identity.c:508: identity_new_from_db_cb
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.170: ../libsignon-glib/signon-identity.c:341: identity_registered: /com/google/code/AccountsSSO/SingleSignOn/Identity_LONGNUMBERTHATPERHAPSSHOULDNTBEHERE_12
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.172: ../libsignon-glib/signon-identity.c:380: identity_registered: 
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.172: ../libsignon-glib/signon-identity-info.c:104: signon_identity_info_new_from_variant: 
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.172: ../libsignon-glib/signon-identity.c:744: identity_store_info_ready_cb 744
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.211: ../libsignon-glib/signon-identity.c:290: State changed to DATA_UPDATED
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.211: ../libsignon-glib/signon-identity.c:929: 929 identity_process_updated
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.225: ../libsignon-glib/signon-identity.c:559: signon_identity_new_from_db 559: 4

** (io.elementary.switchboard:8237): DEBUG: 11:19:59.234: ../libsignon-glib/signon-identity.c:598: identity_session_object_destroyed_cb 598

** (io.elementary.switchboard:8237): WARNING **: 11:19:59.234: auth_session_set_id_ready_cb returned error: Object disposed
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.235: ../libsignon-glib/signon-identity.c:508: identity_new_from_db_cb
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.235: ../libsignon-glib/signon-identity.c:341: identity_registered: /com/google/code/AccountsSSO/SingleSignOn/Identity_LONGNUMBERTHATPERHAPSSHOULDNTBEHERE_13
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.237: ../libsignon-glib/signon-identity.c:380: identity_registered: 
** (io.elementary.switchboard:8237): DEBUG: 11:19:59.237: ../libsignon-glib/signon-identity-info.c:104: signon_identity_info_new_from_variant: 
** (io.elementary.switchboard:8237): DEBUG: 11:20:04.688: ../libsignon-glib/signon-identity.c:317: identity_remote_object_destroyed_cb 317
```

## Platform Information

Elementary OS 6 early access with latest updates running on Microsoft Surface Pro 4 (i5, 8GB ram)

**Comment by riker09** [comment] 2021-04-13 11:51
The same happens when I enter the credentials to my private IMAP server. And since there is no "Test Connection" button, I cannot verify in advance if I made a mistake when entering my account data.

**Comment by selwynorren** [comment] 2021-05-06 23:27
I have the exact same issue. Loaded private IMAP server and its not connected to anything at all, so when launching mail app, it shows that I need to setup email account, which of course has been done

Running Elementary OS Beta with updates

**Comment by danrabbit** [comment] 2021-05-24 19:57
Thanks for your report! We're doing a from-scratch rewrite of Online Accounts and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Online Accounts.

**Closed by danrabbit** 2021-05-24 19:57 UTC
